export const COMMON_TEXT = {
  ACTIONS: {
    SAVE: 'Save',
    CANCEL: 'Cancel',
    SUBMIT: 'Submit',
    DELETE: 'Delete',
    EDIT: 'Edit',
    CLOSE: 'Close',
    SEARCH: 'Search...',
    FILTER: 'Filter',
    EXPORT: 'Export',
    IMPORT: 'Import',
    REFRESH: 'Refresh',
    LOADING: 'Loading...',
    CONFIRM: 'Confirm',
    BACK: 'Back',
    NEXT: 'Next',
  },
  STATUS: {
    ACTIVE: 'Active',
    INACTIVE: 'Inactive',
    PENDING: 'Pending',
    COMPLETED: 'Completed',
    SUCCESS: 'Success',
    ERROR: 'Error',
    WARNING: 'Warning',
    INFO: 'Info',
  },
  MESSAGES: {
    GENERIC_ERROR: 'Something went wrong. Please try again.',
    NO_DATA: 'No records found.',
    UNAUTHORIZED: 'You are not authorized to perform this action.',
    NETWORK_ERROR: 'Network error. Please check your connection.',
  },
} as const;
