export const AUTH_TEXT = {
  LOGIN: {
    HEADING: 'Sign In to Your Account',
    SUB_HEADING: 'Enter your credentials to access your dashboard',
    ID_EMAIL_LABEL: 'Email or User ID',
    ID_EMAIL_PLACEHOLDER: 'admin@school.edu or ADM001',
    PASSWORD_LABEL: 'Password',
    PASSWORD_PLACEHOLDER: 'Enter your password',
    REMEMBER_ME: 'Remember me',
    FORGOT_PASSWORD: 'Forgot Password?',
    SIGN_IN_BTN: 'Sign In',
  },
  SIGNUP: {
    HEADING: 'Create New Account',
    SUB_HEADING: 'Join the school management system platform',
    FULL_NAME_LABEL: 'Full Name',
    FULL_NAME_PLACEHOLDER: 'John Doe',
    EMAIL_LABEL: 'Email Address',
    EMAIL_PLACEHOLDER: 'john.doe@school.edu',
    PHONE_LABEL: 'Phone Number',
    PHONE_PLACEHOLDER: '+91 98765-43210',
    PASSWORD_LABEL: 'Password',
    PASSWORD_PLACEHOLDER: 'Create strong password',
    CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Re-enter password',
    ROLE_LABEL: 'Account Role',
    SIGNUP_BTN: 'Create Account',
  },
  FORGOT: {
    HEADING: 'Reset Password',
    SUB_HEADING: 'Enter your email to receive password reset instructions',
    EMAIL_LABEL: 'Email Address',
    EMAIL_PLACEHOLDER: 'enter your registered email',
    SUBMIT_BTN: 'Send Reset Link',
    BACK_TO_LOGIN: 'Back to Login',
    SUCCESS_MSG: 'Reset instructions have been sent to your email address.',
  },
  TOGGLE: {
    HAVE_ACCOUNT: 'Already have an account?',
    NO_ACCOUNT: "Don't have an account?",
    SIGN_IN_LINK: 'Sign in here',
    SIGN_UP_LINK: 'Register here',
  },
} as const;
